site_name: Training guide for physicist
site_description: Lecture note style documetnation for useful skill in physics 
site_author: Kaze Wong
repo_url: https://github.com/kazewong/Training_guide_for_physicist
repo_name: kazewong/kazewong

theme:
    name: material
    features:
        - navigation  # Sections are included in the navigation on the left.
        - toc  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: deep purple
          accent: green
          toggle:
             icon: material/brightness-5
             name: Dark mode
        - scheme: slate
          primary: custom
          accent: purple
          toggle:
             icon: material/brightness-2
             name: Light mode

    twitter_name: "@physicskaze"
    twitter_url: "https://twitter.com/physicskaze"

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mkdocs-jupyter: # Jupyter notebook support
        # show_input: False
    - literate-nav:
        nav_file: SUMMARY.md
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()

                optional:
                    inherited_members: true  # Allow looking up inherited methods
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4

extra_css:
  - stylesheets/extra.css

nav:
    - Home: index.html
    - Mathematics: 
      - Analysis:
        - Mathematics/Calculus/Calculus.md
      - Probability and Statistics:
        - Mathematics/ProbabilityAndStatistics/ProbabilityAndStatistics.md
      - Discrete Mathematics:
        - Mathematics/DiscreteMathematics/DiscreteMathematics.md
      - Linear Algebra: 
        - Mathematics/LinearAlgebra/LinearAlgebra.md
        - Mathematics/LinearAlgebra/LinearAlgebra2.md
    - Physics: 
      - Classical Mechanics:
        - Physics/ClassicalMechanics/ClassicalMechanics.md
        - Physics/ClassicalMechanics/ClassicalMechanics2.md
      - Electromagnetism:
        - Physics/Electromagnetism/Electromagnetism.md
        - Physics/Electromagnetism/Electromagnetism2.md
      - Quantum Mechanics:
        - Physics/QuantumMechanics/QuantumMechanics.md
        - Physics/QuantumMechanics/QuantumMechanics2.md
      - Statistical Mechanics:
        - Physics/StatisticalMechanics/StatisticalMechanics.md
        - Physics/StatisticalMechanics/StatisticalMechanics2.md
    - Computing:
      - Hardware:
        - Computing/Hardware/Hardware.md
      - Algorithm:
        - Computing/Algorithm/Algorithm.md
